<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fnn_address"
 *
 * Auto generated by Extension Builder 2014-09-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Address Organisation Tool',
	'description' => 'This address organisation tool is developed to help store a little more complex address data and display it. It is possible to create organisations and persons and because of the relations between them and the possibility to combine them into groups.',
	'category' => 'plugin',
	'author' => '599media',
	'author_email' => 'info@599media.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.1-6.2.99',
            'extbase' => '6.2.1',
            'fluid' => '6.2.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
            'static_info_tables' => '6.1',
		),
	),
);